name: Build and test

on:
  push:
    branches:
      - debug-build-refactor.2-winheap

jobs:

  windows:
    name: Build and test (Windows)
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Install conan
      run: |
        pip install conan
        conan profile new tket --detect
        conan profile update options.tket:shared=True tket
    - name: Build symengine
      run: conan create --profile=tket recipes/symengine
    - name: Build tket
      run: conan create --profile=tket --test-folder=None recipes/tket
