name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - test-pybind11-abort.1
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'

jobs:

  macos-m1:
    name: Build and test (MacOS M1)
    runs-on: [self-hosted, macos, M1]
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name == github.repository
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    env:
      PYTKET_SKIP_REGISTRATION: "true"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up conan
      id: conan
      run: |
        conan profile new tket --detect --force
        export CC=`which conan`
        echo "CONAN_CMD=${CC}" >> $GITHUB_ENV
    - name: Build symengine
      run: conan create --profile=tket --build=missing recipes/symengine
    - name: Build tket
      run: conan create --profile=tket recipes/tket
    - name: Build pytket (3.8)
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.8
        OPENBLAS="$(brew --prefix openblas)" pip install -U scipy
        cd pytket
        pip install -e . -v
        python -c "import pytket"
    - name: Build pytket (3.9)
      if: github.event_name == 'push'
      run: |
        eval "$(pyenv init -)"
        pyenv shell tket-3.9
        OPENBLAS="$(brew --prefix openblas)" pip install -U scipy
        cd pytket
        pip install -e . -v
        python -c "import pytket"
