name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - test-fiasco
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'

jobs:

  macos-m1:
    name: Build and test (MacOS M1)
    runs-on: [self-hosted, macos, M1]
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event.pull_request.head.repo.full_name == github.repository
    defaults:
      run:
        shell: "/usr/bin/arch -arch arm64e /bin/bash {0}"
    env:
      PYTKET_SKIP_REGISTRATION: "true"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up conan
      id: conan
      run: |
        conan profile new tket --detect --force
        export CC=`which conan`
        echo "CONAN_CMD=${CC}" >> $GITHUB_ENV
    - name: Install boost
      run: conan install --profile=tket boost/1.77.0@ --build=missing -o boost:without_fiber=True -o boost:without_json=True -o boost:without_nowide=True
    - name: Build symengine
      run: conan create --profile=tket recipes/symengine -o boost:without_fiber=True -o boost:without_json=True -o boost:without_nowide=True
    - name: Build tket
      run: conan create --profile=tket recipes/tket -o boost:without_fiber=True -o boost:without_json=True -o boost:without_nowide=True
    - name: Build and run tket tests
      run: conan create --profile=tket recipes/tket-tests -o boost:without_fiber=True -o boost:without_json=True -o boost:without_nowide=True
    - name: Build and run tket proptests
      run: conan create --profile=tket recipes/tket-proptests -o boost:without_fiber=True -o boost:without_json=True -o boost:without_nowide=True
    - name: Set up Python 3.8
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build pytket (3.8)
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: |
        OPENBLAS="$(brew --prefix openblas)" pip install -U scipy
        cd pytket
        pip install -e . -v
    - name: Test pytket (3.8)
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: |
        cd pytket/tests
        pip install -r requirements.txt
        pytest --ignore=simulator/ --doctest-modules
    - name: Set up Python 3.9
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build pytket (3.9)
      if: github.event_name == 'push'
      run: |
        OPENBLAS="$(brew --prefix openblas)" pip install -U scipy
        cd pytket
        pip install -e . -v
    - name: Test pytket (3.9)
      if: github.event_name == 'push'
      run: |
        cd pytket/tests
        pip install -r requirements.txt
        pytest --ignore=simulator/ --doctest-modules

  windows:
    name: Build and test (Windows)
    runs-on: windows-2019
    env:
      PYTKET_SKIP_REGISTRATION: "true"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Hash bubble source
      id: hash_bubble_source
      run: |
        Function Get-FolderHash
        {
            param ($folder)
            $files = dir $folder -Recurse |? { -not $_.psiscontainer }
            $allBytes = new-object System.Collections.Generic.List[byte]
            foreach ($file in $files)
            {
                $allBytes.AddRange([System.IO.File]::ReadAllBytes($file.FullName))
                $allBytes.AddRange([System.Text.Encoding]::UTF8.GetBytes($file.Name))
            }
            $hasher = [System.Security.Cryptography.MD5]::Create()
            $ret = [string]::Join("",$($hasher.ComputeHash($allBytes.ToArray()) | %{"{0:x2}" -f $_}))
            return $ret
        }
        $bubble_hash = Get-FolderHash bubble
        echo "::set-output name=bubble_hash::${bubble_hash}"
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Install conan
      run: |
        pip install conan
        conan profile new tket --detect
        $conan_cmd = (gcm conan).Path
        echo "CONAN_CMD=${conan_cmd}" >> $GITHUB_ENV
    - name: Build symengine
      run: conan create --profile=tket recipes/symengine
    - name: Build tket
      run: conan create --profile=tket recipes/tket
    - name: Build and run tket tests
      run: conan create --profile=tket recipes/tket-tests
    - name: Build and run tket proptests
      run: conan create --profile=tket recipes/tket-proptests
    - name: Set up Python 3.7
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build and test pytket (3.7)
      if: github.event_name == 'push'
      run: |
        cd pytket
        pip install -e . -v
        cd tests
        pip install -r requirements.txt
        pip install -r requirements-openfermion.txt
        pytest --ignore=simulator/ --doctest-modules
    - name: Set up Python 3.8
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build and test pytket (3.8)
      if: github.event_name == 'push'
      run: |
        cd pytket
        pip install -e . -v
        cd tests
        pip install -r requirements.txt
        pip install -r requirements-openfermion.txt
        pytest --ignore=simulator/ --doctest-modules
    - name: Set up Python 3.9
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build and test pytket (3.9)
      if: github.event_name == 'push'
      run: |
        cd pytket
        pip install -e . -v
        cd tests
        pip install -r requirements.txt
        pip install -r requirements-openfermion.txt
        pytest --ignore=simulator/ --doctest-modules
